### PR TITLE
some small adjustments

### PR DESCRIPTION
**Pull request by bgruening**
@eschen42 the help text in your data params are had to understand imho.

```
variable x sample, decimal: '.', missing: NA, mode: numerical, separator: tab
```

The tab, should be clear as it is format=tabular, the decimal should hopefully also be standard, the mode will not be known by most of the people I assume and missing ... mh, maybe relevant. Depends on where you get your data from. I would remove it I guess.

### CODE REVIEW

**Comment by eschen42** [comment]
@bgruening Assuming that I am to ignore the use of a comma as a decimal separator, then how about this?

> Data matrix help: "variable x sample, missing values: NA"
> Sample metadata help: "sample names x metadata columns"
> Variable metadata help: "variable names x metadata columns"

I committed some changes to the head prior to noting your PR. I notice now that your .travis.yml file includes the .tt_blacklist references that cause Travis to fail because I don't have the .tt_blacklist file.
Apart from that, my .travis.yml is the same, but **it passes on Travis even though I have set one of the tests to fail deliberately**.  It seems to me that there are some assumptions in Travis about how my repo is laid out and used; specifically, that I have several tools in my repo (I don't) and that there is something to trigger addition of something to `changed_tools_chunk.list` or `changed_repositories_chunk.list` (there isn't).   Therefore, **I don't know whether .travis.yml works for some other system or scenario, but my Travis-build-on-checkin does not tell me that my test will fail under that scenario**.  It also seems to have code for updating the toolshed; I want to make that decision myself rather than automatically updating the toolshed on every release.

> Edit: It looks to me like this is the .travis.yml from [https://github.com/galaxyproject/tools-iuc](https://github.com/galaxyproject/tools-iuc).  From the looks of [http://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/management.html#manual-management](http://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/management.html#manual-management), it looks like I am following the manual management track, for two reasons (1) the reason that I cited above and (2) the fact that I want a Zenodo DOI per tool, and Zenodo seems to assign a DOI per repository.

Also, your .gitignore seems to replace my own - can I *append* your .gitignore rather than *replacing* mine?

**Comment by bgruening** [comment]
I think the main issue is that we assume tools in a `tools` folder. Thats probably the reason why the tests are passing. The travis.yaml was only meant as a start if you can enable travis testing I can work on this more. Indeed if you want DOI for every tool you probably need to go the single-repo approach, which comes with more maintenance, but this is up to you. 

> Also, your .gitignore seems to replace my own - can I append your .gitignore rather than replacing mine?

Sure.

> sample names x metadata columns

I do not understand what this means? Is it `sample-names <tab> x <tab> metadata-columns`?

**Comment by eschen42** [comment]
@bgruening  Regarding help text "sample names x metadata columns", what I am trying to communicate to the user is that it is a matrix with one row for each sample name and one column for each sample metadatum.

As I have used these tools and taught others, I found it puzzling at times to keep track of how the data matrix is laid out with respect to the sample metadata and variable metadata; this is why I wanted these help labels.
Perhaps a [multiplication sign](https://en.wikipedia.org/wiki/Multiplication_sign) might make it more readily understood.  What do you think?

**Comment by eschen42** [comment]
I will experiment with the effect of putting my tool into a `tools` folder.

**Comment by bgruening** [comment]
> is a matrix with one row for each sample name and one column for each sample metadatum

I guess if you write it like that it is more understandable :)
Write it as a sentence is enough I think.

**Comment by bgruening** [comment]
@eschen42 one argument for the automatic push from the master branch is, that a reviewer can be sure that the master branch is what you see in the TS. Otherwise, both are out of sync and its hard to know why or request a manual push from you.

**Comment by eschen42** [comment]
@bgruening In the long term, then, I will consider automating commits to master and developing/evaluating on branches, which is practice that I believe in anyway. 

When I can get to it, where is it documented how I would automate deployment - wiring in the tool shed API key, etc.?

**Comment by eschen42** [comment]
This has been handled elsewhere, e.g., in commit 2cd4b5fbeafe30c2b6f4dbbbdcdcf09efe2670f8

**Pull request closed without merging**
